### ISSUE TITLE
Blog Post 

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/terraform-mean-cloudrun-mongodb#14]
Write a blog post about this project including things like the engineering decisions and the logic behind them.

**Comment by thagomizer** [comment]
https://cloud.google.com/blog/products/application-development/deploy-nosql-javascript-web-applications-to-google-cloud/

**Comment by bleything** [comment]
also this: https://cloud.google.com/blog/topics/developers-practitioners/easy-deployment-mean-stack-w-mongodb-atlas-cloud-run-and-hashicorp-terraform
