### ISSUE TITLE
CI/CD Pipeline

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/terraform-mean-cloudrun-mongodb#15]
Build a CI/CD Pipeline to support both testing and subsequent deployments. 
This will also support regenerating static assets.

**Comment by subfuzion** [comment]
See also #12

**Comment by bleything** [comment]
Given the time available, I think we keep it super simple and focused on delivery. Here's what I'm thinking, from the user's perspective... this can happen either the first time they run terraform or after they've already deployed the main demo:

1. fork sample app repo
2. add repo details to `terraform.tfvars` and enable building the pipeline
3. run terraform, which sets up the necessary services, SAs, and IAM roles and configures a Cloud Build trigger to watch the repo
4. push to repo and watch as it is deployed

I think we should handle the testing stuff separately and come back and hook it up to this if we have time. I'm the wrong person to build out the testing system anyway. Someone else should pick that up and work on it in a parallel branch.

@thagomizer @subfuzion: what do you think?

@villasenor: anything I'm missing or should be prepared for?

**Comment by villasenor** [comment]
@bleything Maybe I'm a bit confused here, but how does #18 enable CI/CD? Are you saying that in the future we can add functionality that will check that variable and setup CI/CD if it is enabled?

As far as CI/CD goes, I would normally do some basic Terraform linting and validation, do a `terraform plan` and check for a proper exit code, and then if that CI passes, literally just run `terraform apply -auto-approve` for the CD portion. This can run anywhere, but ideally in Cloud Build. I'm not sure how authentication would work for this pipeline - I haven't done that in an automated fashion on GCP yet. But if it's anything like most providers, it shouldn't be too bad. A sandbox environment that is locked down can be good for this.

**Comment by bleything** [comment]
@villasenor 

> Are you saying that in the future we can add functionality that will check that variable and setup CI/CD if it is enabled?

Yep, #18 is WIP; I just made a simple commit so I could open the PR.

> As far as CI/CD goes, I would normally do some basic Terraform linting and validation, do a terraform plan and check for a proper exit code, and then if that CI passes, literally just run terraform apply -auto-approve for the CD portion.

Ah I think we might have some crossed wires. The goal of this feature is to make Terraform provision a CI/CD pipeline for the demo application, not to add CI for this repo specifically. It'd probably good to have both at some point, but building a deployment pipeline for the demo application is more important right now.

Sorry that wasn't clear before, that's my bad. I'll clarify in the PR so we have that info for future reference.

**Comment by villasenor** [comment]
@bleything Ahh I see. No worries - sorry for assuming! Ok in that case, I think everything you described is perfect for CD. I would add _some_ testing though so that there is a CI component. That could even be linting - the point is that there is a "placeholder" for that type of functionality - showing where it would go and how the flow works.

**Comment by bleything** [comment]
@villasenor: oh that's a really good point about having a placeholder for a more robust testing environment down the road. I'll plan on adding a linting step and we can expand on it later. Thank you!
