### ISSUE TITLE
Identify tasks to be automated

### ISSUE THREAD

**Issue by subfuzion** [GoogleCloudPlatform/terraform-mean-cloudrun-mongodb#4]
Referring to #3, identify the steps that need to be automated by Terraform.

MVP prerequisites:

1. User has a single app container image already pushed to an image repository. On container deployment, the app reads the `ATLAS_URI` environment variable to connect to the database.
2. User has a GCP billing account ID and an organization ID.
3. User has installed [gcloud](https://cloud.google.com/sdk/docs/install-sdk).
4. User has a MongoDB Atlas account organization ID and API keys.
5. User has installed [Terraform](https://www.terraform.io/downloads).
6. User has identified the GCP and Atlas region for deployment.

High level script task requirements:

- [x] Ability to create app/database infrastructure, deploy app, and provide user with app URL.
- [x] Verify successful deployment. See #12 (app URL probably enough verification for single container deploy)
- [x] Ability to tear down app/database infrastructure.

**Comment by bleything** [comment]
let's track this in #8.

**Comment by subfuzion** [comment]
+1 for tracking automation steps in #8. I still want to keep the issue open (using for milestone tracking). Can close this when the PR is closed.
